name: Deploy Express App

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd my-express-server &&
            git pull &&
            echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" > .env &&
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env &&
            echo "CORS_ORIGIN=${{ secrets.CORS_ORIGIN }}" >> .env &&
            npm install &&
            pm2 reload my-express-server || pm2 start server.js --name my-express-server --watch
